[package]
name = "state-client-lib"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
offchain-utils = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }

state-fold-types = { path = "../state-fold-types" }
state-server-common = { path = "../state-server-common", features = ["server"] }

async-trait = "0.1"
tonic = "0.6"
tokio = { version = "1", features = ["sync"] }
tokio-stream = "0.1"

serde = "1"
serde_json = "1"
snafu = "0.6"
