[package]
name = "state-client-lib"
license = "Apache-2.0"
version = "0.3.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = ["cartesi"]

[dependencies]
state-fold-types = { version = "0.3", registry = "cartesi", path = "../state-fold-types", features = ["ethers"] }
state-server-common = { version = "0.3", registry = "cartesi", path = "../state-server-common", features = ["server"] }

async-trait = "0.1"
tonic = "0.7"
tokio = { version = "1", features = ["sync"] }
tokio-stream = "0.1"

serde = "1"
serde_json = "1"
snafu = "0.7"
