[package]
name = "eth-state-client-lib"
license = "Apache-2.0"
version = "0.6.3"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
eth-state-fold-types = { workspace = true, features = ["ethers"] }
eth-state-server-common = { workspace = true, features = ["server"] }

async-trait = "0.1"
tonic = "0.8"
tokio = { version = "1", features = ["sync"] }
tokio-stream = "0.1"

serde = "1"
serde_json = "1"
snafu = "0.7"
clap = { version = "4.1", features = ["derive", "env"] }
