[package]
name = "state-fold-types"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
offchain-utils = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }
