[package]
name = "eth-state-fold-types"
license = "Apache-2.0"
version = "0.6.3"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
serde = "1"
ethers = { version = "1.0", optional = true, features = ["ws", "abigen", "rustls"] }
ethabi = { version = "18" }
serde_json = "1"
toml = "0.5.8"
anyhow = "1"
proc-macro2 = "1"
quote = "1"
snafu = "0.7"
