[package]
name = "state-fold-types"
license = "Apache-2.0"
version = "0.2.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = ["cartesi"]

[dependencies]
serde = "1"
ethers = { version = "0.6", optional = true, features = ["ws"] }
ethabi = { version = "16" }
serde_json = "1"
anyhow = "1"
proc-macro2 = "1"
quote = "1"
snafu = "0.7"
