[package]
name = "eth-state-fold-test"
license = "Apache-2.0"
version = "0.6.3"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = false

[dependencies]
eth-state-fold-types = { workspace = true }
hex = "0.4"
serde_json = "1.0"
async-trait = "0.1"
tokio = { version = "^1.5", features = ["sync"] }

[build-dependencies]
eth-state-fold-types = { workspace = true, features = ["ethers"] }
serde_json = "1"
anyhow = "1"
proc-macro2 = "1"
