[package]
name = "state-fold-test"
license = "Apache-2.0"
version = "0.5.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = false

[dependencies]
state-fold-types = { path = "../state-fold-types" }
hex = "0.4"
serde_json = "1.0"
async-trait = "0.1"
tokio = { version = "^1.5", features = ["sync"] }

[build-dependencies]
state-fold-types = { path = "../state-fold-types", features = ["ethers"] }
serde_json = "1"
anyhow = "1"
proc-macro2 = "1"
