[package]
name = "eth-state-server-common"
license = "Apache-2.0"
version = "0.6.3"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
include = [
    "build.rs",
    "**/*.rs",
    "Cargo.toml",
    "grpc-interfaces/*.proto"
]

[features]
default = ["client"]
server = []
client = []

[dependencies]
eth-state-fold-types = { workspace = true }

prost = "0.11"
tonic = "0.8"

serde = "1"
serde_json = "1"
snafu = "0.7"


[build-dependencies]
tonic-build = "0.8"
anyhow = "1"
