[package]
name = "state-server-common"
license = "Apache-2.0"
version = "0.2.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = false

[features]
default = ["client"]
server = []
client = []

[dependencies]
state-fold-types = { version = "0.2", registry = "cartesi", path = "../state-fold-types" }

prost = "0.10"
tonic = "0.7"

serde = "1"
serde_json = "1"
snafu = "0.7"


[build-dependencies]
tonic-build = "0.7"
