[package]
name = "eth-state-fold"
license = "Apache-2.0"
version = "0.6.3"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
eth-state-fold-types = { workspace = true, features = ["ethers"] }
eth-block-history = { workspace = true }

snafu = "0.7"
clap = { version = "4.1", features = ["derive", "env"] }

async-recursion = "1"
async-trait = "0.1"
futures = "0.3"
tokio = { version = "^1.5", features = ["sync"] }


[dev-dependencies]
eth-state-fold-test = { workspace = true }
tokio = { version = "^1.5", features = ["macros"] }
matches = "0.1"
