[package]
name = "state-fold"
license = "Apache-2.0"
version = "0.2.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = ["cartesi"]

[dependencies]
state-fold-types = { version = "0.2", registry = "cartesi", path = "../state-fold-types", features = ["ethers"] }

async-trait = "0.1"
futures = "0.3"
tokio = { version = "^1.5", features = ["sync"] }
toml = "0.5.8"

serde = "1.0.0"
serde_json = "1"
snafu = "0.7"
structopt = "0.3"

[dev-dependencies]
state-fold-test = { path = "../state-fold-test" }
tokio = { version = "^1.5", features = ["macros"] }
