[package]
name = "state-fold"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
offchain-utils = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }

structopt = "0.3"
serde = "1.0.0"

async-trait = "0.1"
futures = "0.3"
snafu = "0.6"
tokio = { version = "^1.5", features = ["sync"] }

[dev-dependencies]
ethers = { version = "0.5.3", features = [ "legacy", "ws" ] }
ethers-core = { version = "^0.5.0", features = [ "legacy" ] }
ethers-contract = { version = "^0.5.0", features = [ "legacy" ] }
ethers-providers = { version = "^0.5.0", features = [ "ws" ] }
offchain-utils = { git = "https://github.com/cartesi/offchain-utils", tag = "v0.1.0" }

hex = "0.4.3"
serde_json = "1.0"
tokio = { version = "^1.5", features = ["macros"] }
