[package]
name = "state-fold"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Cartesi Team"]
homepage = "https://cartesi.io"
edition = "2018"

[dependencies]
offchain-utils = { git = "https://github.com/cartesi/offchain-utils", rev = "c4a9c05" }

async-trait = "0.1"
futures = "0.3"
tokio = { version = "^1.5", features = ["sync"] }

serde = "1.0.0"
snafu = "0.6"
structopt = "0.3"

[dev-dependencies]
ethers = { version = "0.5.3" }
ethers-contract = { version = "^0.5.0" }
ethers-core = { version = "^0.5.0" }
ethers-providers = { version = "^0.5.0" }
ethers-signers = { version = "^0.5.0" }
ethers-middleware = { version = "^0.5.0" }

serde_json = "1.0"
hex = "0.4.3"

tokio = { version = "^1.5", features = ["macros"] }
