[package]
name = "eth-block-history"
license = "Apache-2.0"
version = "0.6.3"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
eth-state-fold-types = { workspace = true, features = ["ethers"] }

snafu = "0.7"
clap = { version = "4.1", features = ["derive", "env"] }

async-stream = "0.3"
tokio = { version = "1", features = ["sync", "macros"] }
tokio-stream = "0.1"
tracing = "0.1"


[dev-dependencies]
eth-state-fold-test = { workspace = true }

async-trait = "0.1"
tokio = { version = "1", features = ["macros"] }
