[package]
name = "state-server-lib"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"

[dependencies]
block-history = { path = "../block-history" }
state-server-common = { path = "../state-server-common", features = ["server"] }
state-fold = { path = "../state-fold" }
state-fold-types = { path = "../state-fold-types" }

futures = "0.3"
tonic = "0.6"
tonic-health = "0.5"
tokio = { version = "1", features = ["sync", "signal"] }
tokio-stream = "0.1"
serde = "1"
serde_json = "1"
snafu = "0.6"
