[package]
name = "state-server-lib"
license = "Apache-2.0"
version = "0.6.1"
authors = ["Gabriel Coutinho de Paula <gabriel.coutinho@cartesi.io>"]
homepage = "https://cartesi.io"
edition = "2021"
publish = ["cartesi"]

[dependencies]
block-history = { version = "0.6", registry = "cartesi", path = "../block-history" }
state-server-common = { version = "0.6", registry = "cartesi", path = "../state-server-common", features = ["server"] }
state-fold = { version = "0.6", registry = "cartesi", path = "../state-fold" }
state-fold-types = { version = "0.6", registry = "cartesi", path = "../state-fold-types" }

futures = "0.3"
tonic = "0.8"
tonic-health = "0.7"
tokio = { version = "1", features = ["sync", "signal"] }
tokio-stream = "0.1"
tracing = "0.1"
serde = "1"
serde_json = "1"
snafu = "0.7"
structopt = "0.3"
